### ISSUE TITLE
determine FALCON version

### ISSUE THREAD

**Issue by zhk2017** [PacificBiosciences/FALCON#602]
How to determine FALCON version?

cd FALCON-integrate 
git rev-parse HEAD

return value is : 7498ef9d9454d606a90bfe06f41548c09d78a0ab

but i don't know the version is?

**Comment by skingan** [comment]
Hi zhk2017,
The commit ID is the best way to identify the version of the software. We release new versions less regularly so the best way to identify the exact code base is to use the commit ID.
Sarah

**Comment by pb-cdunn** [comment]
Also, `falcon_kit.egg-info/PKG-INFO`, e.g.
```yaml
Metadata-Version: 1.0
Name: falcon-kit
Version: 1.0+git.11e9c21db4d8b9d9aa6cf1db148782298680e1eb
```


    python -c 'import pkg_resources, falcon_kit; print pkg_resources.get_distribution("falcon-kit").version'
    1.0+git.11e9c21db4d8b9d9aa6cf1db148782298680e1eb
